import{S as L,a as q,i as c}from"./assets/vendor-_xVQgjhV.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const d=document.querySelector(".gallery"),v=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function u(r){const o=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:n,views:y,comments:g,downloads:b})=>`
          <a href="${e}" class="gallery-item">
            <img src="${a}" alt="${t}" loading="lazy" />
            <div class="info">
              <p><b>Likes:</b> ${n}</p>
              <p><b>Views:</b> ${y}</p>
              <p><b>Comments:</b> ${g}</p>
              <p><b>Downloads:</b> ${b}</p>
            </div>
          </a>`).join("");d.insertAdjacentHTML("beforeend",o),v.refresh();const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}function S(){d.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}const w="45241203-3832c115afebf1441ca7c88b6",$="https://pixabay.com/api/";async function f(r,o=1){try{return(await q.get($,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(s){iziToast.error({position:"topRight",message:`${s}`})}}let i=1,h="";const E=document.querySelector(".search-form"),l=document.querySelector(".load-more");l.classList.add("hidden");E.addEventListener("submit",async r=>{r.preventDefault();const o=r.currentTarget.elements.query,s=o.value.trim();if(!s){c.error({message:"Please enter a search query!",position:"topRight"});return}h=s,i=1,S(),m();try{const a=await f(s,i);a.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(u(a.hits),a.totalHits>i*15&&l.classList.remove("hidden"))}catch(a){c.error({title:"Error",message:a.message})}finally{p(),o.value=""}});l.addEventListener("click",async()=>{i+=1,m();try{const r=await f(h,i);u(r.hits),r.totalHits<=i*15&&(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l.classList.add("hidden"))}catch(r){c.error({title:"Error",message:r.message})}finally{p()}});
//# sourceMappingURL=commonHelpers.js.map
